const tintColorLight: String = '#0C6157';
const tintColorDark: String = '#fff';

export default {
  light: {
    text: 'black',
    headerText: '#231F20',
    subText: '#9E9E9E',
    lightText: '#707070',
    placeholderTextColor: '#424244',
    background: '#ffffff',
    borderColor: '#d7dae2',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    inputBg: '#f8f4f4',
    blue: '#21409A',
  },
  dark: {
    text: 'white',
    background: '#000000',
    lightDark: '#1D1E20',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    borderColor: '#585858',
  },
  button: {
    blue: '#81a7ff',
    grey: 'grey',
  },
  gray: 'gray',
  black: 'black',
  primary: '#FFA557',
  primaryLight: '#FFF2E9',
  secondary: '#FEF1E8',
  background: 'white',
  text: '#231F20',
  headerText: '#231F20',
  subText: '#9E9E9E',
  border: '#D9D9D9',
  alter: '#D5226C',
  placeholder: '#BCBEC0',
  failed: '#e46969',
  alert: 'red',
  success: '#69e4a6',
  green: '#187d48',
  shadow: '#0000000A',
  darkShadow: '#000',
};
