export const states = [
  {short: 'AL', label: 'Alabama', value: 'Alabama', country: 'US'},
  {short: 'AK', label: 'Alaska', value: 'Alaska', country: 'US'},
  {short: 'AZ', label: 'Arizona', value: 'Arizona', country: 'US'},
  {short: 'AR', label: 'Arkansas', value: 'Arkansas', country: 'US'},
  {short: 'CA', label: 'California', value: 'California', country: 'US'},
  {short: 'CO', label: 'Colorado', value: 'Colorado', country: 'US'},
  {short: 'CT', label: 'Connecticut', value: 'Connecticut', country: 'US'},
  {
    short: 'DC',
    label: 'District of Columbia',
    value: 'District of Columbia',
    alt: ['Washington DC', 'Washington D.C.'],
    country: 'US',
  },
  {short: 'DE', label: 'Delaware', value: 'Delaware', country: 'US'},
  {short: 'FL', label: 'Florida', value: 'Florida', country: 'US'},
  {short: 'GA', label: 'Georgia', value: 'Georgia', country: 'US'},
  {short: 'HI', label: 'Hawaii', value: 'Hawaii', country: 'US'},
  {short: 'ID', label: 'Idaho', value: 'Idaho', country: 'US'},
  {short: 'IL', label: 'Illinois', value: 'Illinois', country: 'US'},
  {short: 'IN', label: 'Indiana', value: 'Indiana', country: 'US'},
  {short: 'IA', label: 'Iowa', value: 'Iowa', country: 'US'},
  {short: 'KS', label: 'Kansas', value: 'Kansas', country: 'US'},
  {short: 'KY', label: 'Kentucky', value: 'Kentucky', country: 'US'},
  {short: 'LA', label: 'Louisiana', value: 'Louisiana', country: 'US'},
  {short: 'ME', label: 'Maine', value: 'Maine', country: 'US'},
  {short: 'MD', label: 'Maryland', value: 'Maryland', country: 'US'},
  {short: 'MA', label: 'Massachusetts', value: 'Massachusetts', country: 'US'},
  {short: 'MI', label: 'Michigan', value: 'Michigan', country: 'US'},
  {short: 'MN', label: 'Minnesota', value: 'Minnesota', country: 'US'},
  {short: 'MS', label: 'Mississippi', value: 'Mississippi', country: 'US'},
  {short: 'MO', label: 'Missouri', value: 'Missouri', country: 'US'},
  {short: 'MT', label: 'Montana', value: 'Montana', country: 'US'},
  {short: 'NE', label: 'Nebraska', value: 'Nebraska', country: 'US'},
  {short: 'NV', label: 'Nevada', value: 'Nevada', country: 'US'},
  {short: 'NH', label: 'New Hampshire', value: 'New Hampshire', country: 'US'},
  {short: 'NJ', label: 'New Jersey', value: 'New Jersey', country: 'US'},
  {short: 'NM', label: 'New Mexico', value: 'New Mexico', country: 'US'},
  {short: 'NY', label: 'New York', value: 'New York', country: 'US'},
  {short: 'NC', label: 'North Carolina', value: 'North Carolina', country: 'US'},
  {short: 'ND', label: 'North Dakota', value: 'North Dakota', country: 'US'},
  {short: 'OH', label: 'Ohio', value: 'Ohio', country: 'US'},
  {short: 'OK', label: 'Oklahoma', value: 'Oklahoma', country: 'US'},
  {short: 'OR', label: 'Oregon', value: 'Oregon', country: 'US'},
  {short: 'PA', label: 'Pennsylvania', value: 'Pennsylvania', country: 'US'},
  {short: 'RI', label: 'Rhode Island', value: 'Rhode Island', country: 'US'},
  {short: 'SC', label: 'South Carolina', value: 'South Carolina', country: 'US'},
  {short: 'SD', label: 'South Dakota', value: 'South Dakota', country: 'US'},
  {short: 'TN', label: 'Tennessee', value: 'Tennessee', country: 'US'},
  {short: 'TX', label: 'Texas', value: 'Texas', country: 'US'},
  {short: 'UT', label: 'Utah', value: 'Utah', country: 'US'},
  {short: 'VT', label: 'Vermont', value: 'Vermont', country: 'US'},
  {short: 'VA', label: 'Virginia', value: 'Virginia', country: 'US'},
  {short: 'WA', label: 'Washington', value: 'Washington', country: 'US'},
  {short: 'WV', label: 'West Virginia', value: 'West Virginia', country: 'US'},
  {short: 'WI', label: 'Wisconsin', value: 'Wisconsin', country: 'US'},
  {short: 'WY', label: 'Wyoming', value: 'Wyoming', country: 'US'},
  {short: 'AS', label: 'American Samoa', value: 'American Samoa', country: 'US'},
  {short: 'GU', label: 'Guam', value: 'Guam', country: 'US'},
  {
    short: 'MP',
    label: 'Northern Mariana Islands',
    value: 'Northern Mariana Islands',
    country: 'US',
  },
  {short: 'PR', label: 'Puerto Rico', value: 'Puerto Rico', country: 'US'},
  {
    short: 'UM',
    label: 'United States Minor Outlying Islands',
    value: 'United States Minor Outlying Islands',
    country: 'US',
  },
  {short: 'VI', label: 'Virgin Islands', value: 'Virgin Islands', country: 'US'},
];
